<?php
/**
 * @file
 * Code for the System feature.
 */

include_once 'glacier_system.features.inc';

/**
 * Tell Drupal to also look for template files in glacier features.
 *
 * Implements hook_theme_registry_alter().
 */
function glacier_system_theme_registry_alter(&$theme_registry) {
  if (!path_is_admin(current_path())) {
    $glacier_system_directory = drupal_get_path('module', 'glacier_system');
    // All features that extend glacier must be placed inside the "features" directory.
    $glacier_features_directory = $glacier_system_directory . '/features';
    // Get all features from the features directory.
    $glacier_features_paths = array_filter(glob($glacier_features_directory . '/*'), 'is_dir');
    foreach ($glacier_features_paths as $path) {
      $template_path = $path . '/templates';
      if (is_dir($template_path)) {
        // Find template files.
        $impementations = drupal_find_theme_templates($theme_registry, '.tpl.php', $template_path);
        foreach ($impementations as $key => $impementation) {
          // Add a "type" to prevent an error with the theme() function.
          $impementations[$key]['type'] = 'module';
        }
        // Add template files to the theme registry.
        $theme_registry += $impementations;
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function glacier_system_form_field_ui_display_overview_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['additional_settings']) && isset($form['additional_settings']['ds_layouts'])) {
    foreach ($form['additional_settings']['ds_layouts']['layout']['#options'] as $key => $option) {
      // Remove "fluid" display suite layouts, with glacier every layout is fluid.
      if (strpos($key, 'fluid') !== FALSE) {
        unset($form['additional_settings']['ds_layouts']['layout']['#options'][$key]);
      }
    }
  }

  if (isset($form['fields']['title_field'])) {
    // Remove the display suite title field if the title field
    // from the "title" Drupal module, is already active.
    unset($form['fields']['title']);
    unset($form['#ds_fields'][0]);
  }
}
