<?php
/**
 * @file
 * Code for the System feature.
 */

include_once 'glacier_system.features.inc';

/**
 * Tell Drupal to also look for template files in glacier module folders.
 *
 * Implements hook_theme_registry_alter().
 */
function glacier_system_theme_registry_alter(&$theme_registry) {
  if (!path_is_admin(current_path())) {
    $modules = module_list();
    foreach ($modules as $module) {
      if (_glacier_system_starts_with($module, 'glacier_')) {
        $path  = drupal_get_path('module', $module) . '/templates';
        $theme_registry += drupal_find_theme_templates($theme_registry, '.tpl.php', $path);
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function glacier_system_form_field_ui_display_overview_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['additional_settings']) && isset($form['additional_settings']['ds_layouts'])) {
    foreach ($form['additional_settings']['ds_layouts']['layout']['#options'] as $key => $option) {
      // Remove "fluid" display suite layouts, with glacier every layout is fluid.
      if (strpos($key, 'fluid') !== FALSE) {
        unset($form['additional_settings']['ds_layouts']['layout']['#options'][$key]);
      }
    }
  }

  if (isset($form['fields']['title_field'])) {
    // Remove the display suite title field if the title field
    // from the "title" Drupal module, is already active.
    unset($form['fields']['title']);
    unset($form['#ds_fields'][0]);
  }
}

function _glacier_system_starts_with($haystack, $needle) {
  $length = strlen($needle);
  return (substr($haystack, 0, $length) === $needle);
}
